### ISSUE TITLE
adjusting coverage threshold through gulp and lab

### ISSUE THREAD

**Issue by walshe** [stevenjmarsh/hapi-boilerplate#1]
whats the correct format ?

gulp.task('test', function () {
  return gulp.src('test')
    .pipe(lab('-c').pipe(lab('-t')).pipe(lab('90'));
});

**Comment by stevenjmarsh** [comment]
I am not certain what you are asking for, but if you are trying to lower the test coverage threshold to 90 for one test run, the format is `lab -t 90`,

from the command line:
`lab -t 90`
`lab -c -t 90`

examples:
package.json
```
{
  "scripts": {
    "test": "lab -c -t 90",
    "test-cov-html": "lab -r html -o coverage.html"
  }
}
```
gulpfile
```
gulp.task('test', function () {
  return gulp.src('test')
    .pipe(lab('-c -t 90'));
});
```
__NOTE:__ if you are using node version 6 or later, some tests will fail ("leaks detected:Reflect, WebAssembly").

To resolve this, the project packages need to be updated. Those updates cause breaking changes in the current codebase. I will try to update the packages, and address the breaking changes, but will not be able to get to that for at least a week. In the meantime, try the lab arguments examples I listed above, and feel free to experiment with different versions of the packages. You may find a package version that addresses the leak issue, but does not introduce breaking changes.

**Comment by walshe** [comment]
thanks
I did run into some issue with tests. IN the end I had to move toward "lab": "^15.2.0" , but now I got issues with done() no longer being used and async calls being jumped over in the tests e.g. server.inject

**Comment by stevenjmarsh** [comment]
exactly. that's what I ran in to this weekend too. I was thinking, I'd update the packages, and address a few simple breaking changes. But as I updated the packages (especially hapi and lab), I was running in to more significant code changes than I had time for.

**Comment by walshe** [comment]
"lab": "14.x.x",  seems to work pretty good
