### ISSUE TITLE
tool ?

### ISSUE THREAD

**Issue by walshe** [stevenjmarsh/hapi-boilerplate#3]
is there any quick way to format all the code with a library or something ?

**Comment by stevenjmarsh** [comment]
I use a package called prettier, https://prettier.io/.  I like it, but note it is opinionated, and there are not a lot of settings you can set to adjust how the code is formatted. You mostly have to go with how it formats the code. It integrates well with the editor I use too (VS Code).  Prettier is an add-on for a lot of other popular editors as well. (Note, there is prettier-miscellaneous package, which is based on prettier, but provides more formatting options, https://github.com/arijs/prettier-miscellaneous)

Another popular code formatter is beautify, http://jsbeautifier.org/. I haven't used it, but it seems pretty popular. I know VS Code has an extension for it.

Also, if you use eslint for linting, you can configure lint to do some formatting, or run another formatter.
examples: https://medium.com/@netczuk/even-faster-code-formatting-using-eslint-22b80d061461

**Comment by walshe** [comment]
thanks, I used standardjs in the end:

```
  "scripts": {
    "test": "standard && lab -c --threshold 90 --timeout 120000",
    "start": "./bin/www",
    "knex:migrate": "knex migrate:latest",
    "knex:seed": "knex seed:run",
    "format": "standard --fix"
  },
  "standard": {
    "ignore": [
      "public"
    ]
  }
```


```
  "dependencies": {
..
    "standard": "^10.0.3"
  },
```

**Comment by stevenjmarsh** [comment]
Nice. I think it's more important to be using any notable linter / formatter. Which one doesn't matter as much, boils down to preference.
